server:
  port: 8080

spring:
  application:
    name: varun.surf
    version: ${version}
  ai:
    openai:
      api-key: YOUR_API_KEY
      chat:
        options:
          model: gpt-4o-mini
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: smollm2:135m

app:
  feature:
    ai:
      forecast:
        analysis:
          enabled: false
  ai:
    provider: ollama